# https://wiki.hypr.land/Configuring/Environment-variables/

# XDG Specifications
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# System Defaults
env = EDITOR,nvim
env = BROWSER,zen-browser
env = TERM,ghostty 
env = TERMINAL,ghostty
env = PATH,$HOME/.local/bin:$PATH

# Aquamarine Environment Variables 
env = AQ_DRM_DEVICES=,/dev/dri/card2:/dev/dri/card1  # First is primary (AMD 2 NVIDIA 1)

# Toolkit Backend Variables 
env = SDL_VIDEODRIVER,wayland
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# Qt Variables
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct
env = ELECTRON_OZONE_PLATFORM_HINT,auto


# NVIDIA 
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = NVD_BACKEND,direct


env = GDK_SCALE,1
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24