# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    numlock_by_default= true
    follow_mouse = 1

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        scroll_factor = 0.5
        middle_button_emulation = true
    }
}
