misc {
    # https://wiki.hypr.land/Configuring/Variables/#misc
	disable_hyprland_logo = true
    vfr = true
    force_default_wallpaper = 0
    key_press_enables_dpms = true
    mouse_move_enables_dpms = true
    disable_autoreload = true

    focus_on_activate = true

    initial_workspace_tracking = 2 # maybe i should use 1 but need to test 2
    
    size_limits_tiled = true
}
ecosystem {
    # https://wiki.hypr.land/Configuring/Variables/#ecosystem
    no_update_news = true
    no_donation_nag = true
}

quirks {
    # https://wiki.hypr.land/Configuring/Variables/#quirks
    prefer_hdr = 1
}

xwayland {
    # https://wiki.hypr.land/Configuring/Variables/#xwayland
    force_zero_scaling = true
    create_abstract_socket = true
}

cursor {
    # https://wiki.hypr.land/Configuring/Variables/#cursor
    no_hardware_cursors = true
    inactive_timeout = 30
}