# See https://wiki.hyprland.org/Configuring/Monitors/

monitorv2 {
    output = eDP-2
    mode = 2560x1600@165
    position = 0x0
    scale = 1.25
    bitdepth = 10
    
    # HDR and Color Management settings
    supports_wide_color = 1
    supports_hdr = 1
    sdr_max_luminance = 250  # Typical bright-room setting
    sdr_min_luminance = 0.005 # Matches OLED/High-end IPS black levels
}

monitorv2 {
    output = DP-2
    mode = 1440x900@75
    position = auto
    scale = 1.00
}
monitor = , highres, auto, 1
