 ecosystem{
     enforce_permissions=true
 }

 permission = /usr/bin/* , screencopy , ask
 permission = /usr/bin/grim , screencopy , allow
 permission = /usr/bin/hyprlock ,screencopy , allow 
 permission = /usr/bin/discord , screencopy , ask
 permission = /usr/bin/zen-browser , screencopy , ask
 permission = /usr/bin/obs , screencopy , ask
 permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

 permission = /run/media/* , keyboard , deny
