-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("ALT + CTRL + Delete")
hl.bind("ALT + CTRL + Delete", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "Power Menu: Toggle" })
hl.unbind("SUPER + Escape")
hl.bind("SUPER + Escape", hl.dsp.exec_cmd("dms ipc call lock lockAndOutputsOff"))
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { locked = true, description = "Lock Screen" })
hl.unbind("SUPER + Tab")
hl.bind("SUPER + Tab", hl.dsp.exec_cmd("dms ipc call hypr openOverview"), { description = "Hyprland: Open Overview" })
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "Clipboard: Toggle" })
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_cmd("dms ipc call spotlight-bar toggle"), { description = "Spotlight Bar: Toggle" })
hl.unbind("XF86AudioNext")
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("dms ipc call mpris next"), { locked = true, description = "Media: Next Track" })
hl.unbind("XF86AudioPlay")
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true, description = "Media: Play/Pause" })
hl.unbind("XF86AudioPrev")
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("dms ipc call mpris previous"), { locked = true, description = "Media: Previous Track" })
hl.unbind("XF86AudioStop")
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("dms ipc call mpris stop"), { locked = true, description = "Media: Stop" })
hl.unbind("XF86MonBrightnessDown")
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5 \"\""), { locked = true, repeating = true, description = "Brightness Down (5%)" })
hl.unbind("XF86MonBrightnessUp")
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5 \"\""), { locked = true, repeating = true, description = "Brightness Up (5%)" })
hl.unbind("XF86Search")
hl.bind("XF86Search", hl.dsp.exec_cmd("dms ipc call spotlight-bar toggle"), { locked = true, description = "Spotlight Bar: Toggle" })
hl.unbind("SUPER + I")
hl.bind("SUPER + I", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"), { locked = true, description = "Settings: Focus or Toggle" })
