-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:XBH XBH 1234567890", mode = "1920x1080@60.000", position = "1920x0", scale = 1, mirror = "eDP-1" })
hl.monitor({ output = "desc:Samsung Electric Company SAMSUNG 0x01000E00", mode = "3840x2160@30.000", position = "1920x0", scale = 1, mirror = "eDP-1" })
hl.monitor({ output = "desc:EDO LEN151WQXGA", mode = "2560x1600@165.000", position = "0x0", scale = 1.33203125, vrr = 0, bitdepth = 10 })
hl.monitor({ output = "desc:Dell Inc. DELL S1709W K437D9AD4CGL", mode = "1440x900@59.887", position = "1920x0", scale = 1, vrr = 0 })
